scrape_configs:
  - job_name: 'prometheus'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 15s
    static_configs:
      - targets: ['host.docker.internal:8080']

#global:
#  scrape_interval: 5s
#
#scrape_configs:
#  - job_name: "k6"
#    static_configs:
#      - targets:
#          - "k6:6565"
